version: "3"
services:
  cardb:
    image: postgres:latest
    container_name: postgres_carsDB
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: carsDB
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      local:
  elasticsearch:
    image: elasticsearch:8.7.0
    container_name: elasticsearch_lab2
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elastic_lab2:/usr/share/elasticsearch/data
    networks:
      local:

  kibana:
    image: kibana:8.7.0
    container_name: kibana_lab2
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    depends_on:
      - elasticsearch
    networks:
      local:

  logstash:
    image: logstash:8.7.0
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5044:5044"
      - "6000:5000/tcp"
      - "6000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      local:
    depends_on:
      - elasticsearch
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

networks:
  local:
    driver: bridge
volumes:
  elastic_lab2:
    driver: local
  pg_data:
    driver: local